### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by umetake820** [umetake820/chat-space#10]
# IPアドレス
18.180.38.58

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①サイドバーのピンクの枠で囲った部分の文字位置、文字の大きさをカリキュラム通りにしましょう！**
<img width="313" alt="スクリーンショット 2020-05-20 10 10 18" src="https://user-images.githubusercontent.com/49669977/82393738-3ee76700-9a82-11ea-85b1-78fd75e6d6fd.png">


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by umetake820** [comment]
修正致しました！
ご確認お願いします。

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます！！
上記についてはバッチリ修正されておりました！ありがとうございます‼︎

今一度挙動確認させて頂いたところ、追加で４点修正いただきたい箇所がございましたのでご対応をお願い致します。

**〜参考〜**

https://master.tech-camp.in/curriculums/3944

**[修正箇所]**

**①サイドバーのグループごとの間隔及び、メッセージごとの間隔を調整しましょう。**

<img width="1042" alt="グループと最新メッセージ" src="https://user-images.githubusercontent.com/65144927/82398230-49f3c480-9a8d-11ea-8858-b8acf11759bb.png">


<img width="1043" alt="メッセージ幅" src="https://user-images.githubusercontent.com/65144927/82398241-5415c300-9a8d-11ea-8ebc-7be7e10344ab.png">

**②投稿メッセージの名前とメッセージの文字の大きさと太さを調整しましょう。**

**③EditボタンとEditの文字の位置が若干ズレてしまっているようなので、今一度テキストを見て確認してみましょう。**

<img width="772" alt="Editボタン" src="https://user-images.githubusercontent.com/65144927/82398428-c5ee0c80-9a8d-11ea-865c-fee7a742eb7f.png">

**④テキストをみて投稿フォームを修正しましょう。**」

<img width="691" alt="投稿フォーム見本" src="https://user-images.githubusercontent.com/65144927/82398473-e322db00-9a8d-11ea-8e08-fea457f211b2.png">


<img width="1440" alt="修正！！！" src="https://user-images.githubusercontent.com/65144927/82398489-eddd7000-9a8d-11ea-82f2-614f62e85fa1.png">

<img width="1440" alt="見本" src="https://user-images.githubusercontent.com/65144927/82398750-85db5980-9a8e-11ea-9217-68b9461ea76a.png">



修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by umetake820** [comment]
修正致しました！
ご確認お願いします。

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます！
修正の確認できました‼︎素晴らしいです！！
他に修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！
